brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

# NameServer 地址（宿主机可访问）
namesrvAddr=192.168.211.132:9876

# 关键：显式指定 Broker 对外暴露 IP，避免注册为容器内网 IP 导致外部连接失败
brokerIP1=192.168.211.132
listenPort=10911

# 可选：自动创建主题与订阅组（学习环境建议开启，生产请按需关闭）
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
